//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

    public partial class Building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Building ( )
        {
            this.Flats = new HashSet<Flat>();
        }

        public int Id { get; set; }

        [DisplayName("Площадь дома")]
        public decimal Square { get; set; }

        [DisplayName("Количество этажей")]
        public int Flat_numbers { get; set; }

        [DisplayName("Адрес")]
        public string Address { get; set; }

		[DisplayName("Имя управляющей компании")]
		public int Managment_company_id { get; set; }
    
        public virtual Managment_company Managment_company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flat> Flats { get; set; }
    }
}
