//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class Flat
	{
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flat()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int Id { get; set; }
		[DisplayName("Номер квартиры")]
		public int Flat_number { get; set; }
		[DisplayName("Площадь")]
		public decimal Flat_square { get; set; }

		[DisplayName("Адрес")]
		public int Building_id { get; set; }
		[DisplayName("Фамилия владельца")]
		public int Flat_owner_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Building Building { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
